# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_export_shapefile <- function(raster_path, dest, class_value, neighborhoodExtractCC, neighborhoodExploreCC, computeIndices) {
    invisible(.Call(`_intra_rcpp_export_shapefile`, raster_path, dest, class_value, neighborhoodExtractCC, neighborhoodExploreCC, computeIndices))
}

rcpp_get_patches <- function(raster_path, class_value, neighborhoodExtractCC, neighborhoodExploreCC) {
    .Call(`_intra_rcpp_get_patches`, raster_path, class_value, neighborhoodExtractCC, neighborhoodExploreCC)
}

rcpp_landscape_summary <- function(raster_path, class_value, neighborhoodExtractCC, neighborhoodExploreCC) {
    .Call(`_intra_rcpp_landscape_summary`, raster_path, class_value, neighborhoodExtractCC, neighborhoodExploreCC)
}

